name: Normalize trailing spaces

on:
  push:
    branches:
      - "published"

jobs:
  Normalize-trailing-spaces:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Hong-test repository
        uses: actions/checkout@v3
        with:
          path: bilara-data-integrity/bilara-data

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5

      - name: Execute python script
        run: |
          python .scripts/normalize_trailing_spaces.py
        working-directory: bilara-data-integrity/bilara-data

      - name: Push changed files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Normalize trailing spaces"
          git push origin published:published
        working-directory: bilara-data-integrity/bilara-data
